### PR TITLE
fix: add organizationId to projects:get output

### PR DESCRIPTION
**Pull request by grof**
I put OrganizationID last so that it also appears last in the CSV output to avoid changing the order of columns in the output. If not for that, I would have inserted it between "Name" and "LanguageTopic". Thoughts?

### CODE REVIEW

**Comment by oliver-daniel** [comment]
No matter where you put the new column, this change will necessitate downstream communication with users since it will theoretically 'break' consumers. So, putting it at the end is fine. If we really wanted to go nuts, we could discuss having PKs *always* go at the end/beginning of a tabular output, but that's an entirely separate conversation.

The test data will have to be updated to reflect this change in the API, however.

**Comment by grof** [comment]
After discussion, we are keeping organizationId last. End users will be warned of this change in the release notes when it goes to main.

**Review by oliver-daniel — APPROVED** [review]
Looks good.

**Pull request merged**
