### PR TITLE
fix: make consistent use of color in entities commands output

### PR DESCRIPTION
**Pull request by grof**
As I was testing entities commands, I noted where cyan was missing from the output. I also added the project ID where it made sense.

### CODE REVIEW

**Review by oliver-daniel — APPROVED** [review]
Changes look good, and `requestActionMessage` isn't relevant to test cases so no changes are needed there. Interestingly, searching through the project with the regex `\$\{[^c][^h]?[^a]?[^}]*\}` (i.e., all string interpolations that don't start with at least `cha`) turns up a handful of results, some of which appear to be other human-readable messages -- mostly in `jobs` and `intents` commands. (That regex would be much, much simpler if VSCode's regex parser supported negative lookahead.)

Although, I'm starting to get a little bit cautious of how many of our commands have to import  `chalk`. At some point, we might consider appending a `ux` object or similar to `MixCommand` include helpful UX tools like `chalk.red`, `chalk.cyan`, etc, so that we don't need to lug around third-party imports everywhere. That's a separate discussion however :)

**Comment by grof** [comment]
I agree with your suggestion. We will need to correct the output of the other commands to have a consistent approach with wording and color. Using uclif utilities to handle color will free us from a dependency, yes.

**Pull request merged**
